---
row_count: 384
fields:
  Samples:
    - Lane
    - Sample_ID
  Indexes:
    - Pos
    - IndexI7Name
    - IndexI7
    - IndexI5Name
    - IndexI5
    - IndexKitName
  BCLConvert:
    - OverrideCyclesPattern
    - BarcodeMismatchesIndex1
    - BarcodeMismatchesIndex2
    - AdapterRead1
    - AdapterRead2
  ApplicationProfile:
    - ApplicationProfileId
  TestProfile:
    - TestProfileName

required_fields:
  - Lane
  - Sample_ID
  - IndexI7
  - ApplicationProfile
